# Import das bibliotecas

In [1]:
import pandas as pd 
import numpy as np 
from datetime import datetime, timedelta

# Número de amostras e geração temporal

In [2]:
N = 1_365_000
inicio = datetime(2000, 1, 1)

timestamps = [inicio + timedelta(minutes=i*10) for i in range(N)]

In [3]:
timestamps

[datetime.datetime(2000, 1, 1, 0, 0),
 datetime.datetime(2000, 1, 1, 0, 10),
 datetime.datetime(2000, 1, 1, 0, 20),
 datetime.datetime(2000, 1, 1, 0, 30),
 datetime.datetime(2000, 1, 1, 0, 40),
 datetime.datetime(2000, 1, 1, 0, 50),
 datetime.datetime(2000, 1, 1, 1, 0),
 datetime.datetime(2000, 1, 1, 1, 10),
 datetime.datetime(2000, 1, 1, 1, 20),
 datetime.datetime(2000, 1, 1, 1, 30),
 datetime.datetime(2000, 1, 1, 1, 40),
 datetime.datetime(2000, 1, 1, 1, 50),
 datetime.datetime(2000, 1, 1, 2, 0),
 datetime.datetime(2000, 1, 1, 2, 10),
 datetime.datetime(2000, 1, 1, 2, 20),
 datetime.datetime(2000, 1, 1, 2, 30),
 datetime.datetime(2000, 1, 1, 2, 40),
 datetime.datetime(2000, 1, 1, 2, 50),
 datetime.datetime(2000, 1, 1, 3, 0),
 datetime.datetime(2000, 1, 1, 3, 10),
 datetime.datetime(2000, 1, 1, 3, 20),
 datetime.datetime(2000, 1, 1, 3, 30),
 datetime.datetime(2000, 1, 1, 3, 40),
 datetime.datetime(2000, 1, 1, 3, 50),
 datetime.datetime(2000, 1, 1, 4, 0),
 datetime.datetime(2000, 1, 1, 4, 10),
 datetime.datetime(2000, 1, 1, 4, 20),
 datetime.datetime(2000, 1, 1, 4, 30),
 datetime.datetime(2000, 1, 1, 4, 40),
 datetime.datetime(2000, 1, 1, 4, 50),
 datetime.datetime(2000, 1, 1, 5, 0),
 datetime.datetime(2000, 1, 1, 5, 10),
 datetime.datetime(2000, 1, 1, 5, 20),
 datetime.datetime(2000, 1, 1, 5, 30),
 datetime.datetime(2000, 1, 1, 5, 40),
 datetime.datetime(2000, 1, 1, 5, 50),
 datetime.datetime(2000, 1, 1, 6, 0),
 datetime.datetime(2000, 1, 1, 6, 10),
 datetime.datetime(2000, 1, 1, 6, 20),
 datetime.datetime(2000, 1, 1, 6, 30),
 datetime.datetime(2000, 1, 1, 6, 40),
 datetime.datetime(2000, 1, 1, 6, 50),
 datetime.datetime(2000, 1, 1, 7, 0),
 datetime.datetime(2000, 1, 1, 7, 10),
 datetime.datetime(2000, 1, 1, 7, 20),
 datetime.datetime(2000, 1, 1, 7, 30),
 datetime.datetime(2000, 1, 1, 7, 40),
 datetime.datetime(2000, 1, 1, 7, 50),
 datetime.datetime(2000, 1, 1, 8, 0),
 datetime.datetime(2000, 1, 1, 8, 10),
 datetime.datetime(2000, 1, 1, 8, 20),
 datetime.datetime(2000, 1, 1, 8, 30),
 datetime.datetime(2000, 1, 1, 8, 40),
 datetime.datetime(2000, 1, 1, 8, 50),
 datetime.datetime(2000, 1, 1, 9, 0),
 datetime.datetime(2000, 1, 1, 9, 10),
 datetime.datetime(2000, 1, 1, 9, 20),
 datetime.datetime(2000, 1, 1, 9, 30),
 datetime.datetime(2000, 1, 1, 9, 40),
 datetime.datetime(2000, 1, 1, 9, 50),
 datetime.datetime(2000, 1, 1, 10, 0),
 datetime.datetime(2000, 1, 1, 10, 10),
 datetime.datetime(2000, 1, 1, 10, 20),
 datetime.datetime(2000, 1, 1, 10, 30),
 datetime.datetime(2000, 1, 1, 10, 40),
 datetime.datetime(2000, 1, 1, 10, 50),
 datetime.datetime(2000, 1, 1, 11, 0),
 datetime.datetime(2000, 1, 1, 11, 10),
 datetime.datetime(2000, 1, 1, 11, 20),
 datetime.datetime(2000, 1, 1, 11, 30),
 datetime.datetime(2000, 1, 1, 11, 40),
 datetime.datetime(2000, 1, 1, 11, 50),
 datetime.datetime(2000, 1, 1, 12, 0),
 datetime.datetime(2000, 1, 1, 12, 10),
 datetime.datetime(2000, 1, 1, 12, 20),
 datetime.datetime(2000, 1, 1, 12, 30),
 datetime.datetime(2000, 1, 1, 12, 40),
 datetime.datetime(2000, 1, 1, 12, 50),
 datetime.datetime(2000, 1, 1, 13, 0),
 datetime.datetime(2000, 1, 1, 13, 10),
 datetime.datetime(2000, 1, 1, 13, 20),
 datetime.datetime(2000, 1, 1, 13, 30),
 datetime.datetime(2000, 1, 1, 13, 40),
 datetime.datetime(2000, 1, 1, 13, 50),
 datetime.datetime(2000, 1, 1, 14, 0),
 datetime.datetime(2000, 1, 1, 14, 10),
 datetime.datetime(2000, 1, 1, 14, 20),
 datetime.datetime(2000, 1, 1, 14, 30),
 datetime.datetime(2000, 1, 1, 14, 40),
 datetime.datetime(2000, 1, 1, 14, 50),
 datetime.datetime(2000, 1, 1, 15, 0),
 datetime.datetime(2000, 1, 1, 15, 10),
 datetime.datetime(2000, 1, 1, 15, 20),
 datetime.datetime(2000, 1, 1, 15, 30),
 datetime.datetime(2000, 1, 1, 15, 40),
 datetime.datetime(2000, 1, 1, 15, 50),
 datetime.datetime(2000, 1, 1, 16, 0),
 datetime.datetime(2000, 1, 1, 16, 10),
 datetime.datetime(2000, 1, 1, 16, 20),
 datetime.datetime(2000, 1, 1, 16, 30),
 datetime.datetime(2000, 1, 1, 16, 40),
 datetime.datetime(2000, 1, 1, 16, 50),
 datetime.datetime(2000, 1, 1, 17, 0),
 datetime.datetime(2000, 1, 1, 17, 10),
 datetime.datetime(2000, 1, 1, 17, 20),
 datetime.datetime(2000, 1, 1, 17, 30),
 datetime.datetime(2000, 1, 1, 17, 40),
 datetime.datetime(2000, 1, 1, 17, 50),
 datetime.datetime(2000, 1, 1, 18, 0),
 datetime.datetime(2000, 1, 1, 18, 10),
 datetime.datetime(2000, 1, 1, 18, 20),
 datetime.datetime(2000, 1, 1, 18, 30),
 datetime.datetime(2000, 1, 1, 18, 40),
 datetime.datetime(2000, 1, 1, 18, 50),
 datetime.datetime(2000, 1, 1, 19, 0),
 datetime.datetime(2000, 1, 1, 19, 10),
 datetime.datetime(2000, 1, 1, 19, 20),
 datetime.datetime(2000, 1, 1, 19, 30),
 datetime.datetime(2000, 1, 1, 19, 40),
 datetime.datetime(2000, 1, 1, 19, 50),
 datetime.datetime(2000, 1, 1, 20, 0),
 datetime.datetime(2000, 1, 1, 20, 10),
 datetime.datetime(2000, 1, 1, 20, 20),
 datetime.datetime(2000, 1, 1, 20, 30),
 datetime.datetime(2000, 1, 1, 20, 40),
 datetime.datetime(2000, 1, 1, 20, 50),
 datetime.datetime(2000, 1, 1, 21, 0),
 datetime.datetime(2000, 1, 1, 21, 10),
 datetime.datetime(2000, 1, 1, 21, 20),
 datetime.datetime(2000, 1, 1, 21, 30),
 datetime.datetime(2000, 1, 1, 21, 40),
 datetime.datetime(2000, 1, 1, 21, 50),
 datetime.datetime(2000, 1, 1, 22, 0),
 datetime.datetime(2000, 1, 1, 22, 10),
 datetime.datetime(2000, 1, 1, 22, 20),
 datetime.datetime(2000, 1, 1, 22, 30),
 datetime.datetime(2000, 1, 1, 22, 40),
 datetime.datetime(2000, 1, 1, 22, 50),
 datetime.datetime(2000, 1, 1, 23, 0),
 datetime.datetime(2000, 1, 1, 23, 10),
 datetime.datetime(2000, 1, 1, 23, 20),
 datetime.datetime(2000, 1, 1, 23, 30),
 datetime.datetime(2000, 1, 1, 23, 40),
 datetime.datetime(2000, 1, 1, 23, 50),
 datetime.datetime(2000, 1, 2, 0, 0),
 datetime.datetime(2000, 1, 2, 0, 10),
 datetime.datetime(2000, 1, 2, 0, 20),
 datetime.datetime(2000, 1, 2, 0, 30),
 datetime.datetime(2000, 1, 2, 0, 40),
 datetime.datetime(2000, 1, 2, 0, 50),
 datetime.datetime(2000, 1, 2, 1, 0),
 datetime.datetime(2000, 1, 2, 1, 10),
 datetime.datetime(2000, 1, 2, 1, 20),
 datetime.datetime(2000, 1, 2, 1, 30),
 datetime.datetime(2000, 1, 2, 1, 40),
 datetime.datetime(2000, 1, 2, 1, 50),
 datetime.datetime(2000, 1, 2, 2, 0),
 datetime.datetime(2000, 1, 2, 2, 10),
 datetime.datetime(2000, 1, 2, 2, 20),
 datetime.datetime(2000, 1, 2, 2, 30),
 datetime.datetime(2000, 1, 2, 2, 40),
 datetime.datetime(2000, 1, 2, 2, 50),
 datetime.datetime(2000, 1, 2, 3, 0),
 datetime.datetime(2000, 1, 2, 3, 10),
 datetime.datetime(2000, 1, 2, 3, 20),
 datetime.datetime(2000, 1, 2, 3, 30),
 datetime.datetime(2000, 1, 2, 3, 40),
 datetime.datetime(2000, 1, 2, 3, 50),
 datetime.datetime(2000, 1, 2, 4, 0),
 datetime.datetime(2000, 1, 2, 4, 10),
 datetime.datetime(2000, 1, 2, 4, 20),
 datetime.datetime(2000, 1, 2, 4, 30),
 datetime.datetime(2000, 1, 2, 4, 40),
 datetime.datetime(2000, 1, 2, 4, 50),
 datetime.datetime(2000, 1, 2, 5, 0),
 datetime.datetime(2000, 1, 2, 5, 10),
 datetime.datetime(2000, 1, 2, 5, 20),
 datetime.datetime(2000, 1, 2, 5, 30),
 datetime.datetime(2000, 1, 2, 5, 40),
 datetime.datetime(2000, 1, 2, 5, 50),
 datetime.datetime(2000, 1, 2, 6, 0),
 datetime.datetime(2000, 1, 2, 6, 10),
 datetime.datetime(2000, 1, 2, 6, 20),
 datetime.datetime(2000, 1, 2, 6, 30),
 datetime.datetime(2000, 1, 2, 6, 40),
 datetime.datetime(2000, 1, 2, 6, 50),
 datetime.datetime(2000, 1, 2, 7, 0),
 datetime.datetime(2000, 1, 2, 7, 10),
 datetime.datetime(2000, 1, 2, 7, 20),
 datetime.datetime(2000, 1, 2, 7, 30),
 datetime.datetime(2000, 1, 2, 7, 40),
 datetime.datetime(2000, 1, 2, 7, 50),
 datetime.datetime(2000, 1, 2, 8, 0),
 datetime.datetime(2000, 1, 2, 8, 10),
 datetime.datetime(2000, 1, 2, 8, 20),
 datetime.datetime(2000, 1, 2, 8, 30),
 datetime.datetime(2000, 1, 2, 8, 40),
 datetime.datetime(2000, 1, 2, 8, 50),
 datetime.datetime(2000, 1, 2, 9, 0),
 datetime.datetime(2000, 1, 2, 9, 10),
 datetime.datetime(2000, 1, 2, 9, 20),
 datetime.datetime(2000, 1, 2, 9, 30),
 datetime.datetime(2000, 1, 2, 9, 40),
 datetime.datetime(2000, 1, 2, 9, 50),
 datetime.datetime(2000, 1, 2, 10, 0),
 datetime.datetime(2000, 1, 2, 10, 10),
 datetime.datetime(2000, 1, 2, 10, 20),
 datetime.datetime(2000, 1, 2, 10, 30),
 datetime.datetime(2000, 1, 2, 10, 40),
 datetime.datetime(2000, 1, 2, 10, 50),
 datetime.datetime(2000, 1, 2, 11, 0),
 datetime.datetime(2000, 1, 2, 11, 10),
 datetime.datetime(2000, 1, 2, 11, 20),
 datetime.datetime(2000, 1, 2, 11, 30),
 datetime.datetime(2000, 1, 2, 11, 40),
 datetime.datetime(2000, 1, 2, 11, 50),
 datetime.datetime(2000, 1, 2, 12, 0),
 datetime.datetime(2000, 1, 2, 12, 10),
 datetime.datetime(2000, 1, 2, 12, 20),
 datetime.datetime(2000, 1, 2, 12, 30),
 datetime.datetime(2000, 1, 2, 12, 40),
 datetime.datetime(2000, 1, 2, 12, 50),
 datetime.datetime(2000, 1, 2, 13, 0),
 datetime.datetime(2000, 1, 2, 13, 10),
 datetime.datetime(2000, 1, 2, 13, 20),
 datetime.datetime(2000, 1, 2, 13, 30),
 datetime.datetime(2000, 1, 2, 13, 40),
 datetime.datetime(2000, 1, 2, 13, 50),
 datetime.datetime(2000, 1, 2, 14, 0),
 datetime.datetime(2000, 1, 2, 14, 10),
 datetime.datetime(2000, 1, 2, 14, 20),
 datetime.datetime(2000, 1, 2, 14, 30),
 datetime.datetime(2000, 1, 2, 14, 40),
 datetime.datetime(2000, 1, 2, 14, 50),
 datetime.datetime(2000, 1, 2, 15, 0),
 datetime.datetime(2000, 1, 2, 15, 10),
 datetime.datetime(2000, 1, 2, 15, 20),
 datetime.datetime(2000, 1, 2, 15, 30),
 datetime.datetime(2000, 1, 2, 15, 40),
 datetime.datetime(2000, 1, 2, 15, 50),
 datetime.datetime(2000, 1, 2, 16, 0),
 datetime.datetime(2000, 1, 2, 16, 10),
 datetime.datetime(2000, 1, 2, 16, 20),
 datetime.datetime(2000, 1, 2, 16, 30),
 datetime.datetime(2000, 1, 2, 16, 40),
 datetime.datetime(2000, 1, 2, 16, 50),
 datetime.datetime(2000, 1, 2, 17, 0),
 datetime.datetime(2000, 1, 2, 17, 10),
 datetime.datetime(2000, 1, 2, 17, 20),
 datetime.datetime(2000, 1, 2, 17, 30),
 datetime.datetime(2000, 1, 2, 17, 40),
 datetime.datetime(2000, 1, 2, 17, 50),
 datetime.datetime(2000, 1, 2, 18, 0),
 datetime.datetime(2000, 1, 2, 18, 10),
 datetime.datetime(2000, 1, 2, 18, 20),
 datetime.datetime(2000, 1, 2, 18, 30),
 datetime.datetime(2000, 1, 2, 18, 40),
 datetime.datetime(2000, 1, 2, 18, 50),
 datetime.datetime(2000, 1, 2, 19, 0),
 datetime.datetime(2000, 1, 2, 19, 10),
 datetime.datetime(2000, 1, 2, 19, 20),
 datetime.datetime(2000, 1, 2, 19, 30),
 datetime.datetime(2000, 1, 2, 19, 40),
 datetime.datetime(2000, 1, 2, 19, 50),
 datetime.datetime(2000, 1, 2, 20, 0),
 datetime.datetime(2000, 1, 2, 20, 10),
 datetime.datetime(2000, 1, 2, 20, 20),
 datetime.datetime(2000, 1, 2, 20, 30),
 datetime.datetime(2000, 1, 2, 20, 40),
 datetime.datetime(2000, 1, 2, 20, 50),
 datetime.datetime(2000, 1, 2, 21, 0),
 datetime.datetime(2000, 1, 2, 21, 10),
 datetime.datetime(2000, 1, 2, 21, 20),
 datetime.datetime(2000, 1, 2, 21, 30),
 datetime.datetime(2000, 1, 2, 21, 40),
 datetime.datetime(2000, 1, 2, 21, 50),
 datetime.datetime(2000, 1, 2, 22, 0),
 datetime.datetime(2000, 1, 2, 22, 10),
 datetime.datetime(2000, 1, 2, 22, 20),
 datetime.datetime(2000, 1, 2, 22, 30),
 datetime.datetime(2000, 1, 2, 22, 40),
 datetime.datetime(2000, 1, 2, 22, 50),
 datetime.datetime(2000, 1, 2, 23, 0),
 datetime.datetime(2000, 1, 2, 23, 10),
 datetime.datetime(2000, 1, 2, 23, 20),
 datetime.datetime(2000, 1, 2, 23, 30),
 datetime.datetime(2000, 1, 2, 23, 40),
 datetime.datetime(2000, 1, 2, 23, 50),
 datetime.datetime(2000, 1, 3, 0, 0),
 datetime.datetime(2000, 1, 3, 0, 10),
 datetime.datetime(2000, 1, 3, 0, 20),
 datetime.datetime(2000, 1, 3, 0, 30),
 datetime.datetime(2000, 1, 3, 0, 40),
 datetime.datetime(2000, 1, 3, 0, 50),
 datetime.datetime(2000, 1, 3, 1, 0),
 datetime.datetime(2000, 1, 3, 1, 10),
 datetime.datetime(2000, 1, 3, 1, 20),
 datetime.datetime(2000, 1, 3, 1, 30),
 datetime.datetime(2000, 1, 3, 1, 40),
 datetime.datetime(2000, 1, 3, 1, 50),
 datetime.datetime(2000, 1, 3, 2, 0),
 datetime.datetime(2000, 1, 3, 2, 10),
 datetime.datetime(2000, 1, 3, 2, 20),
 datetime.datetime(2000, 1, 3, 2, 30),
 datetime.datetime(2000, 1, 3, 2, 40),
 datetime.datetime(2000, 1, 3, 2, 50),
 datetime.datetime(2000, 1, 3, 3, 0),
 datetime.datetime(2000, 1, 3, 3, 10),
 datetime.datetime(2000, 1, 3, 3, 20),
 datetime.datetime(2000, 1, 3, 3, 30),
 datetime.datetime(2000, 1, 3, 3, 40),
 datetime.datetime(2000, 1, 3, 3, 50),
 datetime.datetime(2000, 1, 3, 4, 0),
 datetime.datetime(2000, 1, 3, 4, 10),
 datetime.datetime(2000, 1, 3, 4, 20),
 datetime.datetime(2000, 1, 3, 4, 30),
 datetime.datetime(2000, 1, 3, 4, 40),
 datetime.datetime(2000, 1, 3, 4, 50),
 datetime.datetime(2000, 1, 3, 5, 0),
 datetime.datetime(2000, 1, 3, 5, 10),
 datetime.datetime(2000, 1, 3, 5, 20),
 datetime.datetime(2000, 1, 3, 5, 30),
 datetime.datetime(2000, 1, 3, 5, 40),
 datetime.datetime(2000, 1, 3, 5, 50),
 datetime.datetime(2000, 1, 3, 6, 0),
 datetime.datetime(2000, 1, 3, 6, 10),
 datetime.datetime(2000, 1, 3, 6, 20),
 datetime.datetime(2000, 1, 3, 6, 30),
 datetime.datetime(2000, 1, 3, 6, 40),
 datetime.datetime(2000, 1, 3, 6, 50),
 datetime.datetime(2000, 1, 3, 7, 0),
 datetime.datetime(2000, 1, 3, 7, 10),
 datetime.datetime(2000, 1, 3, 7, 20),
 datetime.datetime(2000, 1, 3, 7, 30),
 datetime.datetime(2000, 1, 3, 7, 40),
 datetime.datetime(2000, 1, 3, 7, 50),
 datetime.datetime(2000, 1, 3, 8, 0),
 datetime.datetime(2000, 1, 3, 8, 10),
 datetime.datetime(2000, 1, 3, 8, 20),
 datetime.datetime(2000, 1, 3, 8, 30),
 datetime.datetime(2000, 1, 3, 8, 40),
 datetime.datetime(2000, 1, 3, 8, 50),
 datetime.datetime(2000, 1, 3, 9, 0),
 datetime.datetime(2000, 1, 3, 9, 10),
 datetime.datetime(2000, 1, 3, 9, 20),
 datetime.datetime(2000, 1, 3, 9, 30),
 datetime.datetime(2000, 1, 3, 9, 40),
 datetime.datetime(2000, 1, 3, 9, 50),
 datetime.datetime(2000, 1, 3, 10, 0),
 datetime.datetime(2000, 1, 3, 10, 10),
 datetime.datetime(2000, 1, 3, 10, 20),
 datetime.datetime(2000, 1, 3, 10, 30),
 datetime.datetime(2000, 1, 3, 10, 40),
 datetime.datetime(2000, 1, 3, 10, 50),
 datetime.datetime(2000, 1, 3, 11, 0),
 datetime.datetime(2000, 1, 3, 11, 10),
 datetime.datetime(2000, 1, 3, 11, 20),
 datetime.datetime(2000, 1, 3, 11, 30),
 datetime.datetime(2000, 1, 3, 11, 40),
 datetime.datetime(2000, 1, 3, 11, 50),
 datetime.datetime(2000, 1, 3, 12, 0),
 datetime.datetime(2000, 1, 3, 12, 10),
 datetime.datetime(2000, 1, 3, 12, 20),
 datetime.datetime(2000, 1, 3, 12, 30),
 datetime.datetime(2000, 1, 3, 12, 40),
 datetime.datetime(2000, 1, 3, 12, 50),
 datetime.datetime(2000, 1, 3, 13, 0),
 datetime.datetime(2000, 1, 3, 13, 10),
 datetime.datetime(2000, 1, 3, 13, 20),
 datetime.datetime(2000, 1, 3, 13, 30),
 datetime.datetime(2000, 1, 3, 13, 40),
 datetime.datetime(2000, 1, 3, 13, 50),
 datetime.datetime(2000, 1, 3, 14, 0),
 datetime.datetime(2000, 1, 3, 14, 10),
 datetime.datetime(2000, 1, 3, 14, 20),
 datetime.datetime(2000, 1, 3, 14, 30),
 datetime.datetime(2000, 1, 3, 14, 40),
 datetime.datetime(2000, 1, 3, 14, 50),
 datetime.datetime(2000, 1, 3, 15, 0),
 datetime.datetime(2000, 1, 3, 15, 10),
 datetime.datetime(2000, 1, 3, 15, 20),
 datetime.datetime(2000, 1, 3, 15, 30),
 datetime.datetime(2000, 1, 3, 15, 40),
 datetime.datetime(2000, 1, 3, 15, 50),
 datetime.datetime(2000, 1, 3, 16, 0),
 datetime.datetime(2000, 1, 3, 16, 10),
 datetime.datetime(2000, 1, 3, 16, 20),
 datetime.datetime(2000, 1, 3, 16, 30),
 datetime.datetime(2000, 1, 3, 16, 40),
 datetime.datetime(2000, 1, 3, 16, 50),
 datetime.datetime(2000, 1, 3, 17, 0),
 datetime.datetime(2000, 1, 3, 17, 10),
 datetime.datetime(2000, 1, 3, 17, 20),
 datetime.datetime(2000, 1, 3, 17, 30),
 datetime.datetime(2000, 1, 3, 17, 40),
 datetime.datetime(2000, 1, 3, 17, 50),
 datetime.datetime(2000, 1, 3, 18, 0),
 datetime.datetime(2000, 1, 3, 18, 10),
 datetime.datetime(2000, 1, 3, 18, 20),
 datetime.datetime(2000, 1, 3, 18, 30),
 datetime.datetime(2000, 1, 3, 18, 40),
 datetime.datetime(2000, 1, 3, 18, 50),
 datetime.datetime(2000, 1, 3, 19, 0),
 datetime.datetime(2000, 1, 3, 19, 10),
 datetime.datetime(2000, 1, 3, 19, 20),
 datetime.datetime(2000, 1, 3, 19, 30),
 datetime.datetime(2000, 1, 3, 19, 40),
 datetime.datetime(2000, 1, 3, 19, 50),
 datetime.datetime(2000, 1, 3, 20, 0),
 datetime.datetime(2000, 1, 3, 20, 10),
 datetime.datetime(2000, 1, 3, 20, 20),
 datetime.datetime(2000, 1, 3, 20, 30),
 datetime.datetime(2000, 1, 3, 20, 40),
 datetime.datetime(2000, 1, 3, 20, 50),
 datetime.datetime(2000, 1, 3, 21, 0),
 datetime.datetime(2000, 1, 3, 21, 10),
 datetime.datetime(2000, 1, 3, 21, 20),
 datetime.datetime(2000, 1, 3, 21, 30),
 datetime.datetime(2000, 1, 3, 21, 40),
 datetime.datetime(2000, 1, 3, 21, 50),
 datetime.datetime(2000, 1, 3, 22, 0),
 datetime.datetime(2000, 1, 3, 22, 10),
 datetime.datetime(2000, 1, 3, 22, 20),
 datetime.datetime(2000, 1, 3, 22, 30),
 datetime.datetime(2000, 1, 3, 22, 40),
 datetime.datetime(2000, 1, 3, 22, 50),
 datetime.datetime(2000, 1, 3, 23, 0),
 datetime.datetime(2000, 1, 3, 23, 10),
 datetime.datetime(2000, 1, 3, 23, 20),
 datetime.datetime(2000, 1, 3, 23, 30),
 datetime.datetime(2000, 1, 3, 23, 40),
 datetime.datetime(2000, 1, 3, 23, 50),
 datetime.datetime(2000, 1, 4, 0, 0),
 datetime.datetime(2000, 1, 4, 0, 10),
 datetime.datetime(2000, 1, 4, 0, 20),
 datetime.datetime(2000, 1, 4, 0, 30),
 datetime.datetime(2000, 1, 4, 0, 40),
 datetime.datetime(2000, 1, 4, 0, 50),
 datetime.datetime(2000, 1, 4, 1, 0),
 datetime.datetime(2000, 1, 4, 1, 10),
 datetime.datetime(2000, 1, 4, 1, 20),
 datetime.datetime(2000, 1, 4, 1, 30),
 datetime.datetime(2000, 1, 4, 1, 40),
 datetime.datetime(2000, 1, 4, 1, 50),
 datetime.datetime(2000, 1, 4, 2, 0),
 datetime.datetime(2000, 1, 4, 2, 10),
 datetime.datetime(2000, 1, 4, 2, 20),
 datetime.datetime(2000, 1, 4, 2, 30),
 datetime.datetime(2000, 1, 4, 2, 40),
 datetime.datetime(2000, 1, 4, 2, 50),
 datetime.datetime(2000, 1, 4, 3, 0),
 datetime.datetime(2000, 1, 4, 3, 10),
 datetime.datetime(2000, 1, 4, 3, 20),
 datetime.datetime(2000, 1, 4, 3, 30),
 datetime.datetime(2000, 1, 4, 3, 40),
 datetime.datetime(2000, 1, 4, 3, 50),
 datetime.datetime(2000, 1, 4, 4, 0),
 datetime.datetime(2000, 1, 4, 4, 10),
 datetime.datetime(2000, 1, 4, 4, 20),
 datetime.datetime(2000, 1, 4, 4, 30),
 datetime.datetime(2000, 1, 4, 4, 40),
 datetime.datetime(2000, 1, 4, 4, 50),
 datetime.datetime(2000, 1, 4, 5, 0),
 datetime.datetime(2000, 1, 4, 5, 10),
 datetime.datetime(2000, 1, 4, 5, 20),
 datetime.datetime(2000, 1, 4, 5, 30),
 datetime.datetime(2000, 1, 4, 5, 40),
 datetime.datetime(2000, 1, 4, 5, 50),
 datetime.datetime(2000, 1, 4, 6, 0),
 datetime.datetime(2000, 1, 4, 6, 10),
 datetime.datetime(2000, 1, 4, 6, 20),
 datetime.datetime(2000, 1, 4, 6, 30),
 datetime.datetime(2000, 1, 4, 6, 40),
 datetime.datetime(2000, 1, 4, 6, 50),
 datetime.datetime(2000, 1, 4, 7, 0),
 datetime.datetime(2000, 1, 4, 7, 10),
 datetime.datetime(2000, 1, 4, 7, 20),
 datetime.datetime(2000, 1, 4, 7, 30),
 datetime.datetime(2000, 1, 4, 7, 40),
 datetime.datetime(2000, 1, 4, 7, 50),
 datetime.datetime(2000, 1, 4, 8, 0),
 datetime.datetime(2000, 1, 4, 8, 10),
 datetime.datetime(2000, 1, 4, 8, 20),
 datetime.datetime(2000, 1, 4, 8, 30),
 datetime.datetime(2000, 1, 4, 8, 40),
 datetime.datetime(2000, 1, 4, 8, 50),
 datetime.datetime(2000, 1, 4, 9, 0),
 datetime.datetime(2000, 1, 4, 9, 10),
 datetime.datetime(2000, 1, 4, 9, 20),
 datetime.datetime(2000, 1, 4, 9, 30),
 datetime.datetime(2000, 1, 4, 9, 40),
 datetime.datetime(2000, 1, 4, 9, 50),
 datetime.datetime(2000, 1, 4, 10, 0),
 datetime.datetime(2000, 1, 4, 10, 10),
 datetime.datetime(2000, 1, 4, 10, 20),
 datetime.datetime(2000, 1, 4, 10, 30),
 datetime.datetime(2000, 1, 4, 10, 40),
 datetime.datetime(2000, 1, 4, 10, 50),
 datetime.datetime(2000, 1, 4, 11, 0),
 datetime.datetime(2000, 1, 4, 11, 10),
 datetime.datetime(2000, 1, 4, 11, 20),
 datetime.datetime(2000, 1, 4, 11, 30),
 datetime.datetime(2000, 1, 4, 11, 40),
 datetime.datetime(2000, 1, 4, 11, 50),
 datetime.datetime(2000, 1, 4, 12, 0),
 datetime.datetime(2000, 1, 4, 12, 10),
 datetime.datetime(2000, 1, 4, 12, 20),
 datetime.datetime(2000, 1, 4, 12, 30),

# Simulação da base com base nas colunas originais

In [4]:
np.random.seed(42) 
umidade = np.clip(np.random.normal(40, 10, N), 10, 90) # distribuição centrada em 40%
ph = np.clip(np.random.normal(6.5, 0.7, N), 4.5, 8.5) # centrado em 6.5
n = np.random.choice([0, 1], size=N, p=[0.15, 0.85])
p = np.random.choice([0, 1], size=N, p=[0.15, 0.85])
k = np.random.choice([0, 1], size=N, p=[0.15, 0.85])
pop = np.round(np.random.uniform(0, 1, N), 2)
rain_3h = np.round(np.random.exponential(1.0, N), 2)

# Bloqueio meteorológico
wx_block = np.where((pop >= 0.6) | (rain_3h >= 2.0), 1, 0)

# Decisão da bomba
pump_state = np.where((umidade < 35) & (ph >= 6.0) & (ph <= 6.8) & (n==1) & (p==1) & (k==1) & (wx_block == 0), 1, 0)

In [5]:
pump_state

array([0, 0, 0, ..., 0, 0, 0], shape=(1365000,))

# DataFrame final

In [6]:
df = pd.DataFrame({
    'timestamp':timestamps, 
    'umidade': umidade, 
    'ph': ph, 
    'nitrogenio': n, 
    'fosforo':p, 
    'postassio': k, 
    'probabilidade_precipitacao': pop, 
    'chuva_3h': rain_3h, 
    'bloqueio_meteorológico': wx_block, 
    'estado_bomba': pump_state
})

In [7]:
df

,timestamp,umidade,ph,nitrogenio,fosforo,postassio,probabilidade_precipitacao,chuva_3h,bloqueio_meteorológico,estado_bomba
0,2000-01-01 00:00:00,44.967142,5.877727,1,1,1,0.36,0.43,0,0
1,2000-01-01 00:10:00,38.617357,6.035197,1,1,1,0.76,0.96,1,0
2,2000-01-01 00:20:00,46.476885,5.813679,1,1,1,0.86,0.13,1,0
3,2000-01-01 00:30:00,55.230299,5.647394,1,1,0,0.37,4.24,1,0
4,2000-01-01 00:40:00,37.658466,7.241370,1,0,1,0.47,0.54,0,0
...,...,...,...,...,...,...,...,...,...,...
1364995,2025-12-14 03:10:00,43.830865,6.541486,1,1,0,0.44,0.61,0,0
1364996,2025-12-14 03:20:00,38.106297,6.282486,1,0,1,0.05,3.65,1,0
1364997,2025-12-14 03:30:00,37.565239,6.716741,1,0,1,0.91,4.39,1,0
1364998,2025-12-14 03:40:00,40.533465,6.388291,1,0,0,0.36,0.11,0,0
1364999,2025-12-14 03:50:00,22.777589,5.293928,1,1,1,0.08,2.15,1,0

# Salvar o DataFrame em CSV

In [8]:
df.to_csv('dados_irrigacao.csv', index=False)
df.sample(10)

,timestamp,umidade,ph,nitrogenio,fosforo,postassio,probabilidade_precipitacao,chuva_3h,bloqueio_meteorológico,estado_bomba
1263028,2024-01-06 00:40:00,43.365815,5.993094,0,1,1,0.14,0.68,0,0
385722,2007-05-02 15:00:00,42.281079,5.721081,1,1,1,0.55,0.69,0,0
720646,2013-09-13 11:40:00,15.233622,6.874455,1,1,1,0.60,0.40,1,0
710378,2013-07-04 04:20:00,28.933366,6.319996,1,1,1,0.38,0.52,0,1
523834,2009-12-16 17:40:00,35.747290,6.801352,1,1,1,0.91,0.01,1,0
148049,2002-10-25 02:50:00,33.084539,6.652774,1,0,1,0.53,0.09,0,0
968574,2018-06-01 05:00:00,38.029227,6.415791,0,0,1,0.94,0.83,1,0
1006640,2019-02-20 13:20:00,18.262001,7.511097,1,0,1,0.07,1.24,0,0
450675,2008-07-26 16:30:00,44.069580,5.104972,1,1,0,0.60,1.18,1,0
459796,2008-09-28 00:40:00,49.544820,6.676021,1,1,1,0.41,1.00,0,0